# -*- mode: ruby -*-
# vi: set ft=ruby :

backends = {
  'backend1' => '11',
  'backend2' => '22',
}

balancers = {
  'balancer1' => '111',
  'balancer2' => '122',
}

clients = {
  'client1' => '150',
}

Vagrant.configure("2") do |config|
  config.vm.network "private_network", virtualbox__intnet: true, auto_config: false
  config.vm.box = "bento/ubuntu-20.04"
	config.vm.provider "virtualbox" do |v|
		v.cpus = 1
		v.memory = 512
	end

  backends.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "shell" do |s|
        s.inline = "hostname $1;"\
          "ip addr add $2 dev eth1;"\
          "ip link set dev eth1 up;"\
          "apt -y install nginx;"\
          "sysctl -w net.ipv4.conf.all.arp_ignore=1;"\
          "sysctl -w net.ipv4.conf.all.arp_announce=2;"
        s.args = [k, "172.28.128.#{v}/24"]
      end
    end
  end

  balancers.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "shell" do |s|
        s.inline = "hostname $1;"\
          "ip addr add $2 dev eth1;"\
          "ip link set dev eth1 up;"\
          "apt -y install ipvsadm keepalived;"
        s.args = [k, "172.28.128.#{v}/24"]
      end
    end
  end

  clients.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "shell" do |s|
        s.inline = "hostname $1;"\
          "ip addr add $2 dev eth1;"\
          "ip link set dev eth1 up;"
        s.args = [k, "172.28.128.#{v}/24"]
      end
    end
  end

end