Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.provider "virtualbox" do |v|
		v.cpus = 1
		v.memory = 512
	end
	config.vm.network "forwarded_port", guest: 10234, host: 10234
end
